---

- name: "awslogs | ec2 instance facts collection"
  ec2_instance_facts:
    region: "us-east-2"
    filters:
      "tag:Name": '{{ ansible_nodename }}'
  register: instance_facts

- set_fact:
    i_facts: '{{ instance_facts }}'

- name: "awslogs | copy configuration"
  template: 
    src: awslogs.conf.j2 
    dest: '{{ awslogs_directory }}/awslogs.conf'

